#!/bin/sh

#used to give scripts access to libraries
export PYTHONPATH=$PYTHONPATH:/var/nlp/spring16/teams/Nietzsche/nlp-final-project/Libraries
export PYTHONPATH=$PYTHONPATH:/var/nlp/spring16/teams/Nietzsche/nlp-final-project/QuestionGenerating

python nlp-final-project/Questioning/ask.py "$1" "$2"
